#!/bin/sh

alias ka="killall" \
	mkd="mkdir -pv" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="$FILE" \
	g="git" \
	e="$EDITOR" \
	v="$EDITOR" \
	n="$EDITOR" \
    vim="$EDITOR" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner" \
	src="source venv/bin/activate" \
	dev=". ~/.local/bin/tools/listprojects" \
	ll="ls -al" \
	lsd='ls -l | grep "^d"' \
    ping='ping -c 5'

# GIT aliases
alias \
    gs="git status" \
    gp='git pull' \
    cg='cd `git rev-parse --show-toplevel`' \
    ga="git add" \
    gc="git commit -m" \
    gb=". ~/.local/bin/tools/listbranches" \
    gpu="git push" \
    gsync="git pull origin develop" \
    gl='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit' \

# Python aliases
alias \
    pir="pip -r requirements.txt" \
    venv="python -m venv venv && src"


# Download all posts from a WP blog
dw-blog() {
	wget      --recursive   --mirror   --no-clobber      --exclude-directories=category,author,comments,feed,tag,feed,wp-content,wp-json,newsletter            --html-extension      --convert-links      --domains $1      --no-parent $1
}

vf() { fzf | xargs -r -I % $EDITOR % ;}

# shortcuts
alias \
    h="cd ~/ && ls -a" \
    d="cd ~/Documents && ls -a" \
    D="cd ~/Downloads && ls -a" \
    m="cd ~/Music && ls -a" \
    pp="cd ~/Pictures && ls -a" \
    vv="cd ~/Videos && ls -a" \
    cf="cd ~/.config && ls -a" \
    sc="cd ~/.local/bin && ls -a" \
    mn="cd /mnt && ls -a" \
    bf="$EDITOR ~/.config/bmfiles" \
    bd="$EDITOR ~/.config/bmdirs" \
    cfb="$EDITOR ~/.bashrc" \
    cfa="$EDITOR ~/.config/aliasrc" \
    cfz="$EDITOR ~/.config/zathura/zathurarc" \
    cfv="$EDITOR ~/.config/nvim/init.vim" \
    cfi="$EDITOR ~/.config/i3/config" \
    cfm="$EDITOR ~/.config/mutt/muttrc" \
    eb="$EDITOR ~/Documents/LaTeX/uni.bib" \
    cv="$EDITOR ~/Documents/LaTeX/cv.tex" \
    cfd="$EDITOR ~/.Xdefaults" \
    cfu="$EDITOR ~/.config/newsboat/urls" \
    cfn="$EDITOR ~/.config/newsboat/config" \
    cfmb="$EDITOR ~/.config/ncmpcpp/bindings" \
    cfmc="$EDITOR ~/.config/ncmpcpp/config" \
    er="$EDITOR ~/Documents/referbib" \
    cfB="$EDITOR ~/.config/i3blocks/config" \
    cfk="$EDITOR ~/.config/sxhkd/sxhkdrc" \
