#!/bin/sh

# Add dev shortcuts. Are work specific so won't be put in git repo
export DEVALIAS=~/.config/dev_aliasrc
test -f $DEVALIAS && source $DEVALIAS

alias ka="killall" \
	mkd="mkdir -pv" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="$FILE" \
	g="git" \
	e="$EDITOR" \
	v="$EDITOR" \
    vim="$EDITOR" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner" \
	src="source venv/bin/activate" \
	dev=". ~/.local/bin/tools/listprojects" \
	ll="ls -al" \
	lsd='ls -l | grep "^d"' # List only directories

# GIT aliases
alias gs="git status"
alias gp='git pull'
alias cg='cd `git rev-parse --show-toplevel`' # Go to top level in git project directory
alias ga="git add"
alias gc="git commit -m"
alias gb="git branch"
alias gpu="git push"
alias gsync="git pull origin develop"
alias gl='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit'


# Stop after sending count ECHO_REQUEST packets #
alias ping='ping -c 5'

# cd into directory and run ls
cl() {
	local dir="$1"
	local dir="${dir:=$HOME}"
	if [[ -d "$dir" ]]; then
		cd "$dir" >/dev/null; ls -hal --color=auto
	else
		echo "bash: cl: $dir: Directory not found"
	fi
}

# Download all posts from a WP blog
dw-blog() {
	wget      --recursive   --mirror   --no-clobber      --exclude-directories=category,author,comments,feed,tag,feed,wp-content,wp-json,newsletter            --html-extension      --convert-links      --domains $1      --no-parent $1
}

vf() { fzf | xargs -r -I % $EDITOR % ;}

# shortcuts
alias h="cd ~/ && ls -a" \
d="cd ~/Documents && ls -a" \
D="cd ~/Downloads && ls -a" \
m="cd ~/Music && ls -a" \
pp="cd ~/Pictures && ls -a" \
vv="cd ~/Videos && ls -a" \
cf="cd ~/.config && ls -a" \
sc="cd ~/.local/bin && ls -a" \
mn="cd /mnt && ls -a" \
bf="$EDITOR ~/.config/bmfiles" \
bd="$EDITOR ~/.config/bmdirs" \
cfb="$EDITOR ~/.bashrc" \
cfa="$EDITOR ~/.config/aliasrc" \
cfz="$EDITOR ~/.zshrc" \
cfv="$EDITOR ~/.config/nvim/init.vim" \
cfi="$EDITOR ~/.config/i3/config" \
cfm="$EDITOR ~/.config/mutt/muttrc" \
eb="$EDITOR ~/Documents/LaTeX/uni.bib" \
cv="$EDITOR ~/Documents/LaTeX/cv.tex" \
cfd="$EDITOR ~/.Xdefaults" \
cfu="$EDITOR ~/.config/newsboat/urls" \
cfn="$EDITOR ~/.config/newsboat/config" \
cfmb="$EDITOR ~/.config/ncmpcpp/bindings" \
cfmc="$EDITOR ~/.config/ncmpcpp/config" \
er="$EDITOR ~/Documents/referbib" \
cfB="$EDITOR ~/.config/i3blocks/config" \
cfk="$EDITOR ~/.config/sxhkd/sxhkdrc" \
