#!/bin/sh
alias ka="killall" \
	mkd="mkdir -pv" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	calcurse="calcurse -D ~/.config/calcurse" \
	magit="nvim -c MagitOnly" \
	p="sudo pacman" \
	SS="sudo systemctl" \
	f="$FILE" \
	g="git" \
	trem="transmission-remote" \
	e="$EDITOR" \
	v="$EDITOR" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	gua="git remote | xargs -L1 git push --all" \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	ffmpeg="ffmpeg -hide_banner" \
	src="source venv/bin/activate" \
	dev=". ~/.config/scripts/listprojects.sh" \
	ll="ls -al"

# GIT aliases
alias gs="git status" \
alias gp='git pull'

# Stop after sending count ECHO_REQUEST packets #
alias ping='ping -c 5'

vf() { fzf | xargs -r -I % $EDITOR % ;}
